import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-white text-4xl font-bold">
          Welcome to{' '}
          <a
            className="text-blue-500 text-4xl font-bold"
            href="https://nextjs.org"
          >
            Next.js!
          </a>{' '}
          +{' '}
          <a
            className="text-blue-500 text-4xl font-bold"
            href="https://tailwindcss.com/"
          >
            Tailwind
          </a>
        </h1>

        <p className="text-white mt-10 mr-2">
          Get started by editing{' '}
          <code className="bg-white text-black p-2">pages/index.js</code>
        </p>

        <div className="mt-6">
          <a href="https://ineuron.ai">
            <Image
              src="/logo-light.png"
              height={70}
              width={140}
              alt="ineuron-logo"
            />
          </a>
        </div>
      </main>
    </div>
  );
}
